# Generated by Django 3.2.9 on 2021-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(default='2021-12-12'),
            preserve_default=False,
        ),
    ]
